# Generated by Django 5.0.1 on 2024-02-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mobile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_phone',
            new_name='mobile_number',
        ),
    ]
