# Generated by Django 5.0.1 on 2024-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_mobile_phone_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default='+971'),
        ),
    ]
