# Generated by Django 5.0.1 on 2024-01-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
