# Generated by Django 5.0.1 on 2024-01-29 11:04

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(max_length=10000000, upload_to=category.models.image_upload),
        ),
    ]
