# Generated by Django 5.0.1 on 2024-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
