# Generated by Django 5.0.1 on 2024-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_full_name_order_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(default=1),
        ),
    ]
