# Generated by Django 5.0.1 on 2024-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_phone',
            field=models.IntegerField(default='+971'),
        ),
    ]
